permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: loveshell
  email: kindle@live.cn
  link: http://blog.sectop.org
  weibo: http://weibo.com/opscode
  github: http://github.com/loveshell

# 站点信息
title: 纯净水
description: 很纯的。
url: http://blog.sectop.org
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: blog.sectop.org

# disqus 设置
disqus:
  shortname: sectop

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Security
  - Web
  - OPS
  - Cloud

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
